### ISSUE TITLE
Add some additional way to get to Key Findings from home page

### ISSUE THREAD

**Issue by chrswng** [GovLab/open-data-impact-case-studies#12]
Right now the only way to get there is the button in the middle of the page. A little buried. Should prob have an alternative way to get there. Most likely in top-nav, unless that is too crowded. Any other ideas?

**Comment by claudioccm** [comment]
Added to the top nav. Also fixed some templating non-sense on all the templates, having the same `{% block header %}` no logical reason to have that.
