### ISSUE TITLE
homepage edits

### ISSUE THREAD

**Issue by chrswng** [GovLab/open-data-impact-case-studies#15]
- [x] missing the banner before the 4Ps (originally something like "depends on four enabling conditions")
- [ ] change 10 recommendations section copy (new copy coming from Stefaan)
- [x] "YET, THERE ARE CHALLENGES THAT MUST BE OVERCOME FOR OPEN DATA PROJECTS TO REACH THEIR HIGHEST POTENTIAL" should not have a comma after the YET. (taken from @juliachrusciel's issue, closing that one)

**Comment by claudioccm** [comment]
when we get the new copy, re-open this issue

**Comment by chrswng** [comment]
Stefaan asked for report section to just be "10 RECOMMENDATIONS" and the READ THE REPORT button. Get rid of everything else.

**Comment by tekd** [comment]
Like this?

![screen shot 2016-03-23 at 9 20 43 am](https://cloud.githubusercontent.com/assets/9205941/13986397/9aa48fe4-f0d8-11e5-8da2-df51c2d9dcf4.png)
