### ISSUE TITLE
explore styling

### ISSUE THREAD

**Issue by chrswng** [GovLab/open-data-impact-case-studies#18]
- [ ] white background after header
- [ ] toggle buttons to light grey (inactive) and blue (active) (like homepage)
- [x] lessen padding between buttons and caption
- [x] center captions
- [x] fix all caps caption that appears when page first loads

**Comment by tekd** [comment]
Already fixed the last three. Also got rid of a toggle on the map button.

**Comment by tekd** [comment]
Current state

![screen shot 2016-03-23 at 10 13 58 am](https://cloud.githubusercontent.com/assets/9205941/13987953/41ba8138-f0e0-11e5-9df8-0a38f01a4c28.png)
