### ISSUE TITLE
resources page 

### ISSUE THREAD

**Issue by chrswng** [GovLab/open-data-impact-case-studies#19]
- [x] glossaries table not mobile friendly
- [x] clicking off the modal doesn't close it. only way to close modal is to scroll all the way down to the close button
- [ ] Key Findings not in top nav on resources page

**Comment by ghost** [comment]
1 and 2 done

**Comment by claudioccm** [comment]
There was a `{# block header #}` on every page. I replaced that with a
default header at teh `_base.html`. If we delete the block in the
reources.html file, the default will take place.

**Comment by tekd** [comment]
Ok, I manually added the header in so I can just go remove that block instead and push it back up.
